permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: 조호근(KAI) 학습정리 공간
description: iOS 학습정리하는 공간입니다.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
